############################
#  ACTIVITIES CONTROLLERS  #
############################

### Get all activities
GET http://localhost:8000/api/v1/activities/

### Get activity by ID
GET http://localhost:8000/api/v1/activities/1

### Get acitivity by userID
GET http://localhost:8000/api/v1/activities/user/3

### Add a new activity
POST http://localhost:8000/api/v1/activities/
Content-Type: application/json

{
  "name": "Jumping Jacks",
  "type": "cardio",
  "duration": 30,
  "caloriesBurned": 150,
  "date": "2023-10-02T19:00:00Z",
  "userId": 3
}

### Delete an activity
DELETE http://localhost:8000/api/v1/activities/30

### Update an activity
PUT http://localhost:8000/api/v1/activities/31
Content-Type: application/json

{
  "name": "Running",
  "type": "cardio",
  "duration": 45,
  "caloriesBurned": 400,
  "date": "2023-10-02T19:00:00Z",
  "userId": 3
}

###
POST http://localhost:8000/api/v1/activities/seed

############################
#     USER CONTROLLERS     #
############################

### Get all users
GET http://localhost:8000/api/v1/users/

### Get user by ID
GET http://localhost:8000/api/v1/users/5

### Add a new user
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Smith",
  "email": "smithjames@example.com",
  "age": 45,
  "gender": "male",
  "height": 178,
  "weight": 80,
  "icon": "@/assets/James Smith.svg",
  "role": "user"
}

### Update a user
PUT http://localhost:8000/api/v1/users/5
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Patrick",
  "email": "smithjames@example.com",
  "age": 45,
  "gender": "male",
  "height": 178,
  "weight": 80,
  "icon": "@/assets/James Smith.svg",
  "role": "admin"
}

### Delete a user
DELETE http://localhost:8000/api/v1/users/5

############################
#    ROUTES CONTROLLERS    #
############################

### Get all routes
GET http://localhost:8000/api/v1/routes/

### Get route by ID
GET http://localhost:8000/api/v1/routes/6

### Add a new route
POST http://localhost:8000/api/v1/routes/
Content-Type: application/json

  {
    "name": "Oregon Trail",
    "distance": 15.2,
    "duration": 320,
    "difficulty": "Extreme",
    "description": "A challenging trail through the Oregon wilderness.",
    "startLocation": "Portland, OR",
    "endLocation": "Bend, OR"       
  }

### Update a route
PUT http://localhost:8000/api/v1/routes/6
Content-Type: application/json

{
  "name": "Oregon Trail",
  "distance": 30.5,
  "duration": 320,
  "difficulty": "Extreme",
  "description": "A challenging trail through the Oregon wilderness.",
  "startLocation": "Portland, OR",
  "endLocation": "Bend, OR"
}

### Delete a route
DELETE http://localhost:8000/api/v1/routes/6