
https://localhost:8000/user
###

GET http://localhost:8000/users/
###

GET http://localhost:8000/users/6
###

GET http://localhost:10000/users/search/Gonzalez?limit=10&sort=first_Name&order=asc
###

Get http://localhost:10000/users/search/10
###

POST http://localhost:8000/users/
Content-Type: application/json

{
    "first_Name": "Alec",
    "last_Name": "Arza",
    "age": 22
}
###

PATCH http://localhost:10000/users/10
Content-Type: application/json

{
    "friends_Ids" : [5]
}
###

DELETE http://localhost:8000/users/33
###

POST http://localhost:8000/users/seed
###

PATCH  http://localhost:8000/users/7/addFriend/10

###Summaries test

GET http://localhost:8000/summaries/
###

GET http://localhost:8000/summaries/10
###

GET http://localhost:8000/summaries/search/10?limit=10
###

POST http://localhost:8000/summaries/
Content-Type: application/json

{
    "user_id": 44,
    "name": "Sit ups",
    "note": "afternoon routine",
    "type": "weight",
    "sets": 15,
    "reps": 4
}
###

PATCH http://localhost:8000/summaries/20
Content-Type: application/json

{
    "sets": 25
}
###

DELETE http://localhost:10000/summaries/65
###

POST http://localhost:8000/summaries/seed

### Posts test

GET http://localhost:8000/posts/
###

GET http://localhost:8000/posts/10
###

GET http://localhost:8000/posts/search/4?
###

POST http://localhost:8000/posts/
Content-Type: application/json

{
    "user_Id": 20,
    "summary_Id": 11,
    "content": "good time today",
    "date": "2025-04-25"
}
###

PATCH http://localhost:8000/posts/10
Content-Type: application/json

{
    "date": "2030-05-05"
}
###

DELETE http://localhost:8000/posts/52
###

POST http://localhost:8000/posts/seed
###

###Vue request tests

GET http://localhost:8000/summaries/search/5?